Documentation

diff --git a/selfInstPckg/Makefile b/selfInstPckg/Makefile
--- a/selfInstPckg/Makefile
+++ b/selfInstPckg/Makefile
@@ -1,7 +1,44 @@
+#-------------------------------------------------------------------------------------------------------------------------------
+#                                             __        __   ___           _        _ _ 
+#                                             \ \      / /  |_ _|_ __  ___| |_ __ _| | |
+#                                              \ \ /\ / /____| || '_ \/ __| __/ _` | | |
+#                                               \ V  V /_____| || | | \__ \ || (_| | | |
+#                                                \_/\_/     |___|_| |_|___/\__\__,_|_|_|
+#                                                                                       
+#	
+# Filename: Makefile
+#
+# Author: Silvano Catinella <catinella@yahoo.com>
+#	
+# Description:
+#	This Makefile allows you to create self extracting pakages. Every one of them is composed by a binary part that manages
+#	all installation process, and another component with all archived data and the pre/post-installation scripts, eventually.
+#
+#	+------------------+
+#	| Executable code  |
+#	+------------------+
+#	|                  |
+#	|                  |
+#	| TGZ Archive data |
+#	|                  |
+#	|                  |
+#	+------------------+
+#
+#	WINSTALLCONF
+#	============
+#	All specific data needed to build the package are collected by winstall.sh process and it shares these information
+#	with the self-extractor's installation manager with an header file with all configuration values available as
+#	C symbols. This file must be generated by winstall.sh script execution
+#
+#	This make process is called by winstall.sh script respecting the following syntax:
+#		WINSTALLCONF=<file.h> PRJNAME="<string>" TGZ="<file-name> make
+#
+#-------------------------------------------------------------------------------------------------------------------------------
 
 .PHONY: clean
 
-all:			selfInstaller
+
+all:			$(PRJNAME).bin
 
 selfInstaller:	selfInstaller.o
 			@echo "[ LD ] $@"
@@ -20,9 +57,18 @@ selfInstaller:	selfInstaller.o
 				exit 127;                                             \
 			fi
 
+$(PRJNAME).bin:	selfInstaller $(TGZ)
+			@echo "[SCRIPT] $@"
+			@if [ -n "$(PRJNAME)" ]; then \
+				cat $^ > $@
+			else                                                        \
+				echo "ERROR! PRJNAME is undefined symbol";       \
+				exit 127;                                             \
+			fi
+
 clean:
 			@echo "[CLEAN]"
-			@rm -fv selfInstaller.c selfInstaller.o
+			@rm -fv selfInstaller.c selfInstaller.o selfInstaller
 
 cleanall:		clean
-			@rm -fv selfInstaller
+			@rm -fv $(PRJNAME).bin
